name: Docker-GPR
description: Build, Tag and Push images from a Dockerfile to the GPR

inputs:
  repo-token:
    description: Access token to use the api, use GITHUB_TOKEN silly, it's better
    default: No token was supplied... now you know why things broke!
    required: true
  image-name:
    description: name for Docker image-name
    required: true
  dockerfile-location:
    description: Where in the repo the Dockerfile is located
    default: .
    required: false
  make-latest:
    description: Create a latest tag of this image
    required: false
    default: false
    
outputs:
  imageUrl:
    description: Fully constructed URL to image for use when deploying

runs:
  using: "node12"
  main: main.js
